// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvbdc-AC1ZBqdoQMLCIYRXBRDGVVrps3M',
    appId: '1:528052100662:web:3c890e8b4cb21866ea4297',
    messagingSenderId: '528052100662',
    projectId: 'bbuddy-c1de3',
    authDomain: 'bbuddy-c1de3.firebaseapp.com',
    storageBucket: 'bbuddy-c1de3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuWTcCzham_ahhUlQ24mTK1uBaplwOFLY',
    appId: '1:528052100662:android:35b2fb9283f90d5bea4297',
    messagingSenderId: '528052100662',
    projectId: 'bbuddy-c1de3',
    storageBucket: 'bbuddy-c1de3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ9lPuSJgYSXOps_FrWWQ37haDLlhdeFM',
    appId: '1:528052100662:ios:d85867a0dfaf05c9ea4297',
    messagingSenderId: '528052100662',
    projectId: 'bbuddy-c1de3',
    storageBucket: 'bbuddy-c1de3.appspot.com',
    iosBundleId: 'com.example.bbuddyFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ9lPuSJgYSXOps_FrWWQ37haDLlhdeFM',
    appId: '1:528052100662:ios:ce8c2cb52ea864a8ea4297',
    messagingSenderId: '528052100662',
    projectId: 'bbuddy-c1de3',
    storageBucket: 'bbuddy-c1de3.appspot.com',
    iosBundleId: 'com.example.bbuddyFrontend.RunnerTests',
  );
}
